groups:
  - desktop
  - work
  - dt
  - dt_core
recipes:
  mac_os_x:
    - osxdefaults::disable_auto-correct
    - osxdefaults::disable_natural_scrolling
    - osxdefaults::dock_automatically_hide_and_show_the_dock
    - dotfiles::oh-my-zsh
    - dotfiles::gitconfig
    - change-shell::default
attributes:
  rbenv:
    user_installs:
      - user: 'pr0d1r2'
        rubies:
          - '2.2.3'
          - '2.2.0'
        global: '2.2.3'
        gems:
          '2.2.3':
            - name: 'bundler'
          '2.2.0':
            - name: 'bundler'
        plugins:
          - name: 'rbenv-gem-rehash'
            git_url: 'https://github.com/sstephenson/rbenv-gem-rehash.git'
  change_shell:
    - { username: 'pr0d1r2', shell: '/usr/local/bin/zsh' }
