groups:
  - desktop
  - work
  - dt
  - dt_core
recipes:
  mac_os_x:
    - osxdefaults::check_for_software_updates_daily
    - osxdefaults::disable_auto-correct
    - osxdefaults::disable_disk_image_verification
    - osxdefaults::disable_natural_scrolling
    - osxdefaults::dock_automatically_hide_and_show_the_dock
    - osxdefaults::enable_time_machine_on_unsupported_volumes
    - osxdefaults::expand_print_panel_by_default
    - osxdefaults::expand_save_panel_by_default
    - osxdefaults::finder_allow_text_selection_in_quick_look
    - osxdefaults::finder_automatically_open_a_new_finder_window_when_a_volume_is_mounted
    - osxdefaults::finder_disable_the_warning_before_emptying_the_trash
    - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
    - osxdefaults::finder_display_full_path
    - osxdefaults::finder_search_the_current_folder_by_default
    - osxdefaults::finder_use_list_view_in_all_finder_windows_by_default
    - osxdefaults::increase_sound_quality_for_bluetooth_headphones
    - osxdefaults::increase_window_resize_speed_for_cocoa_applications
    - osxdefaults::menu_add_battery_percentage
    - osxdefaults::menu_show_clock_with_date
    - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
    - osxdefaults::reduce_transparency
    - osxdefaults::save_screenshots_in_png_format
    - osxdefaults::save_screenshots_to_the_desktop
    - osxdefaults::turn_off_keyboard_illumination_when_computer_is_not_used_for_5_minutes
    - osxdefaults::menu_hide
    - dotfiles::oh-my-zsh
    - dotfiles::gitconfig
    - dotfiles::editrc
    - change-shell::default
attributes:
  rbenv:
    user_installs:
      - user: 'pr0d1r2'
        rubies:
          - '2.2.4'
          - '2.2.3'
          - '2.2.0'
        global: '2.2.4'
        plugins:
          - name: 'rbenv-gem-rehash'
            git_url: 'https://github.com/sstephenson/rbenv-gem-rehash.git'
          - name: 'rbenv-charles-ssl'
            git_url: 'https://github.com/mislav/rbenv-charles-ssl.git'
    user_gems:
      '2.2.3':
        - name: 'bundler'
          action: 'install'
      '2.2.0':
        - name: 'bundler'
          action: 'install'
  change_shell:
    - { username: 'pr0d1r2', shell: '/usr/local/bin/zsh' }
