recipes:
  mac_os_x:
    - osxdefaults::set_computer_name
attributes:
  homebrew:
    formulas:
      - htop-osx
      - axel
      - wget
      - youtube-dl
      - homebrew/dupes/rsync
    casks:
      - spotify
      - iterm2
      - hammerspoon
      - commandq
      - tunnelblick
      - torbrowser
      - cleanmymac
    taps:
      - homebrew/dupes
  osxdefaults:
    computername: Sphere
