recipes:
  mac_os_x:
    - osxdefaults::set_computer_name
attributes:
  homebrewalt:
    apps:
      - htop-osx
      - axel
      - wget
    cask_apps:
      - spotify
      - iterm2
  osxdefaults:
    computername: Sphere
