recipes:
  mac_os_x:
    - osxdefaults::set_computer_name
attributes:
  homebrew:
    formulas:
      - htop-osx
      - axel
      - wget
      - youtube-dl
      - homebrew/dupes/rsync
      - homebrew/dupes/openssh
      - x265
      - ncdu
      - watch
      - iozone
    casks:
      - spotify
      - iterm2
      - hammerspoon
      - commandq
      - tunnelblick
      - torbrowser
      - cleanmymac
      - handbrake
    taps:
      - homebrew/dupes
  osxdefaults:
    computername: Sphere
