recipes:
  mac_os_x:
    - ruby-bundle-el-captain-fixes::eventmachine
    - ruby-bundle-el-captain-fixes::puma
attributes:
  homebrewalt:
    apps:
      - pr0d1r2/contrib/wkhtmltopdf-old
      - redis
