recipes:
  mac_os_x:
    - ruby-bundle-el-captain-fixes::eventmachine
    - ruby-bundle-el-captain-fixes::puma
    - ruby-bundle-el-captain-fixes::libv8
attributes:
  homebrew:
    formulas:
      - pr0d1r2/contrib/wkhtmltopdf-old
      - redis
      - graphviz
