recipes:
  global:
    - postgres::default
    - mailhog::default
    - elasticsearch17::default
    - elasticsearch-analysis-icu::default
attributes:
  homebrew:
    formulas:
      - node
      - pkgconfig
      - imagemagick
      - chromedriver
    casks:
      - java
