recipes:
  global:
    - postgres::default
    - mailhog::default
    - elasticsearch17::default
    - elasticsearch-analysis-icu::default
attributes:
  homebrew:
    formulas:
      - node
      - sqlite3
      - pkgconfig
      - imagemagick
      - chromedriver
      - redis
      - awscli
      - node6-lts
      - yarn
    casks:
      - java
      - chromium
