recipes:
  mac_os_x:
    - janus::default
attributes:
  homebrewalt:
    apps:
      - terminal-notifier
      - ack
      - ag
      - git
      - macvim
      - rbenv
      - rbenv-aliases
      - rhash
      - ruby-build
    cask_apps:
      - time-tracker
      - skype
      - google-hangouts
