recipes:
  mac_os_x:
    - janus::default
    - dotjanus::default
    - dotfiles::gemrc
    - ruby_build::default
    - ruby_rbenv::user
attributes:
  homebrew:
    formulas:
      - terminal-notifier
      - ack
      - ag
      - git
      - macvim
      - rpl
      - git-extras
      - ffmpeg
      - python
    casks:
      - time-tracker
      - skype
      - google-hangouts
      - charles
      - sourcetree
      - libreoffice
      - grammarly
      - obs
  rbenv:
    create_profiled: false
  mysql_root_password: "password"
