attributes:
  homebrewalt:
    apps:
      - terminal-notifier
      - ack
      - ag
      - git
      - macvim
      - rbenv
      - rbenv-aliases
      - rhash
      - ruby-build
    cask_apps:
      - time-tracker
