recipes:
  mac_os_x:
    - janus::default
    - dotjanus::default
    - dotfiles::gemrc
    - ruby_build::default
    - ruby_rbenv::user
attributes:
  homebrewalt:
    apps:
      - terminal-notifier
      - ack
      - ag
      - git
      - macvim
    cask_apps:
      - time-tracker
      - skype
      - google-hangouts
  rbenv:
    create_profiled: false
